import { PageShell } from "@/components/layout/PageShell";
import { useEffect, useRef, useState } from "react";
import { Layers } from "lucide-react";

export default function Fractals() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [resolution, setResolution] = useState(400); // 400x400

  // We implement a very basic CPU-based Newton fractal generator
  // For z^3 - 1 = 0
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    canvas.width = resolution;
    canvas.height = resolution;

    const imgData = ctx.createImageData(resolution, resolution);
    const data = imgData.data;

    // The 3 roots of z^3 - 1
    const roots = [
      { r: 1, i: 0, color: [59, 130, 246] }, // Blue
      { r: -0.5, i: Math.sqrt(3)/2, color: [16, 185, 129] }, // Green
      { r: -0.5, i: -Math.sqrt(3)/2, color: [236, 72, 153] }, // Pink
    ];

    const maxIter = 40;
    const tol = 1e-4;

    const zoom = 2;
    const offsetX = 0;
    const offsetY = 0;

    for (let x = 0; x < resolution; x++) {
      for (let y = 0; y < resolution; y++) {
        // Map pixel to complex plane
        let zr = (x - resolution/2) / (resolution/2) * zoom + offsetX;
        let zi = (y - resolution/2) / (resolution/2) * zoom + offsetY;

        let iter = 0;
        for (; iter < maxIter; iter++) {
          // f(z) = z^3 - 1
          // f'(z) = 3z^2
          // z_{n+1} = z - f(z)/f'(z)
          
          const zr2 = zr*zr - zi*zi;
          const zi2 = 2*zr*zi;
          
          const fzr = zr*zr2 - zi*zi2 - 1;
          const fzi = zr*zi2 + zi*zr2;
          
          const dfzr = 3*zr2;
          const dfzi = 3*zi2;
          
          const denom = dfzr*dfzr + dfzi*dfzi;
          if (denom < 1e-10) break;
          
          const div_r = (fzr*dfzr + fzi*dfzi) / denom;
          const div_i = (fzi*dfzr - fzr*dfzi) / denom;
          
          zr -= div_r;
          zi -= div_i;
          
          // Check if converged to any root
          let converged = false;
          for (let i = 0; i < roots.length; i++) {
            const dr = zr - roots[i].r;
            const di = zi - roots[i].i;
            if (dr*dr + di*di < tol) {
              const idx = (y * resolution + x) * 4;
              const shade = 1 - (iter / maxIter);
              data[idx] = roots[i].color[0] * shade;
              data[idx+1] = roots[i].color[1] * shade;
              data[idx+2] = roots[i].color[2] * shade;
              data[idx+3] = 255;
              converged = true;
              break;
            }
          }
          if (converged) break;
        }
        
        if (iter === maxIter) {
          const idx = (y * resolution + x) * 4;
          data[idx] = 0; data[idx+1] = 0; data[idx+2] = 0; data[idx+3] = 255;
        }
      }
    }
    
    ctx.putImageData(imgData, 0, 0);
  }, [resolution]);

  return (
    <PageShell>
      <div className="container py-10 max-w-4xl space-y-8">
        <div className="flex items-center gap-4 border-b border-white/10 pb-6">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-fuchsia-500 to-pink-500 flex items-center justify-center shadow-glow">
            <Layers className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-bold gradient-text">Newton Fractals</h1>
            <p className="text-sm text-muted-foreground mt-1">Visualizing the basins of attraction for Newton's method in the complex plane.</p>
          </div>
        </div>

        <div className="glass p-6 flex flex-col items-center">
          <p className="text-sm text-muted-foreground text-center mb-6 max-w-lg">
            This image is generated by applying Newton's method to the complex function $f(z) = z^3 - 1$. 
            Each pixel represents an initial guess $z_0$. The color indicates which of the 3 roots the guess eventually converges to. The brightness indicates how fast it converged.
          </p>
          
          <div className="rounded-xl overflow-hidden border border-white/20 shadow-glow-lg">
            <canvas ref={canvasRef} className="w-[400px] h-[400px] md:w-[600px] md:h-[600px]" style={{ imageRendering: "pixelated" }} />
          </div>

          <div className="mt-8 flex gap-4">
            <button onClick={() => setResolution(200)} className="px-4 py-2 text-xs rounded-lg border border-white/10 bg-white/[0.05] hover:bg-white/[0.1] transition">Low Res (Fast)</button>
            <button onClick={() => setResolution(400)} className="px-4 py-2 text-xs rounded-lg border border-white/10 bg-white/[0.05] hover:bg-white/[0.1] transition">Med Res</button>
            <button onClick={() => setResolution(800)} className="px-4 py-2 text-xs rounded-lg border border-white/10 bg-white/[0.05] hover:bg-white/[0.1] transition">High Res (Slow)</button>
          </div>
        </div>
      </div>
    </PageShell>
  );
}
